# Generated by Django 4.2.1 on 2023-07-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidebar',
            name='image',
            field=models.ImageField(upload_to='articles/'),
        ),
    ]
