# Generated by Django 4.2.5 on 2024-02-23 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='color',
            new_name='colorcode',
        ),
    ]
