# Generated by Django 4.2.5 on 2024-01-31 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_color_icon_link_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='icon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.icon', verbose_name='Ikonka tanlang: '),
        ),
    ]
