# Generated by Django 4.2.1 on 2023-07-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_delete_topbar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sidebar',
            name='image',
        ),
        migrations.AddField(
            model_name='sidebar',
            name='video',
            field=models.FileField(default=1, upload_to='articles/'),
            preserve_default=False,
        ),
    ]
